  
version: 2.1
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test 
      - run: bash <(curl -s https://codecov.io/bash)
      # - run: flutter -v build apk
